handle converting pr to/from draft
actualbudget/actual-gh-bot pull request #13
Opened 2024-07-07 23:28 UTC by matt-fidd

The assumptions made here are:

- if a PR is a draft, we don't need the `[WIP]` title prefix
- if a PR is a draft, it will always be considered WIP so needs the WIP label
- if a PR is converted from a draft, it should be considered ready for review, and should update as such
- if a PR is converted back to a draft, it should drop the prefix for consistency and revert back to the WIP label
- if a PR is a draft we don't check for failing CI

2024-07-08 15:15 UTC, twk3 requested changes

2024-07-08 15:15 UTC, twk3 commented on src/handlers/pullRequest.ts
> +    if (pr.wip) {
This is probably unnecessary, and might be confusing to the author. If it already had WIP, and converting it to draft made that go away, they might think the bot is confused.

2024-07-08 15:15 UTC, twk3 commented on src/handlers/pullRequest.ts
> +      title = title.substring(6);
Can we use a smarter regex replacement? It's likely what someone (those who use WIP in the title themsevles when they create PRs) will expand our wip regex  to match a few different wip prefixes. Like `WIP: ` but more specifically, to not require the whitespace. Or to have too much whitespace between the wip and title that they would expect trimmed off when we process it like this.

2024-07-08 22:12 UTC, matt-fidd commented
I've addressed your comments, not my finest work hardcoding a length in when it used a regex to match the bit I was removing anyway!

I've also extended the regex to match other common patterns that were previously handled in Trafico so as not to break any folks workflow.

2024-07-09 14:46 UTC, twk3 approved these changes
Great, thanks @matt-fidd !

2024-07-09 18:18 UTC, merged